

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reddit_data
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    depends_on:
      - mysql
    restart: always
    volumes:
      - .:/app  # این باعث میشه تغییرات فایل json دیده بشه
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=reddit_data

  web:
    image: php:apache
    container_name: reddit_web
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql_data:
