FROM python:3.11

# مسیر کاری داخل کانتینر
WORKDIR /app

# کپی پروژه
COPY . /app

# نصب کتابخانه‌های مورد نیاز
RUN pip install mysql-connector-python pymongo textblob neo4j

# دانلود دیتاهای مورد نیاز TextBlob
RUN python -m textblob.download_corpora

# اجرای اسکریپت subscriber
CMD ["python", "subscriber.py"]
