#version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: > 
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reddit_data
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"   # phpMyAdmin روی 8081

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8082:8081"  # mongo-express روی 8082

  neo4j:
    image: neo4j:2025.06.0
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: "neo4j/test1234"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "test1234", "RETURN 1;"]
      interval: 10s
      timeout: 5s
      retries: 5

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    container_name: subscriber
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    restart: always
    volumes:
      - .:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reddit_data
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: test1234

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    container_name: publisher
    depends_on:
      subscriber:
        condition: service_started
    restart: always
    volumes:
      - .:/app
    environment:
      REDDIT_CLIENT_ID: JZHiG9zwTTTFAjtRw3phQ
      REDDIT_SECRET: AOJp98XAKypuAO38fchr3yGeBnAzFQ
      REDDIT_USERNAME: Strange-Molasses-806
      REDDIT_PASSWORD: ghazadd82Am#
      REDDIT_USER_AGENT: SocialMediaAnalysisApp by /u/Strange-Molasses-806

  web:
    image: php:apache
    container_name: reddit_web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: reddit_data
      MYSQL_PORT: 3306
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

volumes:
  mysql_data:
  mongo_data:
  neo4j_data:
