REDDIT_CLIENT_ID = 'JZHiZG9zwTTlFAjtRw3phQ'
REDDIT_SECRET = 'AOJp98XAKypuAO38fchr3yGeBnAzFQ'
REDDIT_USERNAME = 'Strange-Molasses-806'
REDDIT_PASSWORD = 'ghazadd82Am'
REDDIT_USER_AGENT = 'SocialMediaAnalysisApp by /u/Strange-Molasses-806'
